name: Build APK

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  bromine:
    name: Bromine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Show available storage
      shell: bash
      run: df -h

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@v1.1.0
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        swap-storage: true

    - name: Show available storage
      shell: bash
      run: df -h

    - name: Build Bromine in Docker
      run: make bromine

    - name: Upload Bromine APK
      uses: actions/upload-artifact@v3
      with:
        name: bromine.apk
        path: chromium/src/out/Bromine/apks/*.apk
        retention-days: 14

    - name: Show available storage
      shell: bash
      run: df -h

    - name: Show available storage
      shell: bash
      run: df -h
